FROM php:8.0-apache

RUN apt-get update && apt-get install -y  \
    zlib1g-dev  \
    g++  \
    git  \
    libicu-dev  \
    zip  \
    libzip-dev  \
    zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

WORKDIR /var/www/laravel_docker

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer